Order model
SaiyaJ1N/Online-Book-Shop pull request #10
Opened 2023-10-01 14:46 UTC by SaiyaJ1N

2023-10-17 00:14 UTC, Someboty approved these changes

2023-10-17 11:23 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-17 11:23 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/controller/OrderController.java
> +                                              @RequestBody UpdateOrderStatusDto updateRequestDto) {
Will updateRequestDto be validated?

2023-10-17 11:23 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/OrderServiceImpl.java
> +        order.setTotal(shoppingCart.getCartItems().stream()
Please move logic of total order calculation to separate method

2023-10-17 11:23 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/OrderServiceImpl.java
> +        savedOrder.setOrderItems(shoppingCart.getCartItems().stream()
Is it possible to save orderItems together with order entity? (check out cascades)

2023-10-17 11:23 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findById(id).orElseThrow(() ->
Please make sure that the user can retrieve only their own orders, not order created bu other users

2023-10-18 11:46 UTC, andrii-hoienko requested changes
GJ! One minor issue left

2023-10-18 11:46 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/OrderServiceImpl.java
> +        if (!order.getUser().getId().equals(user.getId())) {
1. You should be sure that all interactions with order should be performed by the user that owns an order.
2. OPTIONAL I would prefer to check that order belongs to a specific user on the DB level (modify query to make it return only order that belongs to user by adding additional where for example)

2023-10-18 11:46 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/OrderServiceImpl.java
> +        savedOrder.setOrderItems(shoppingCart.getCartItems().stream()
Discussed in the private channel

2023-10-19 13:22 UTC, andrii-hoienko approved these changes
GJ!

2023-10-20 09:00 UTC, merged