added liquibase to project, added delete method to controller
SaiyaJ1N/Online-Book-Shop pull request #3
Opened 2023-09-06 13:48 UTC by SaiyaJ1N

2023-09-06 15:55 UTC, OleksandrSaven approved these changes
GJ Let's improve this

2023-09-06 15:55 UTC, OleksandrSaven commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  constraints:
you must use default value false for this field

2023-09-08 15:26 UTC, vovasalyha requested changes
GJ. Let's improve it a bit.

2023-09-08 15:26 UTC, vovasalyha commented on src/main/java/com/onlinebookshop/repository/book/BookRepository.java
> +    Optional<Book> findBookById(Long id);
this method is provided by interface `findById`

2023-09-08 15:26 UTC, vovasalyha commented on src/main/java/com/onlinebookshop/repository/book/BookSpecificationProviderManager.java
> +                       new RuntimeException("Can`t find specification provider for the key: "
better use `NoSuchElementException`

2023-09-08 15:26 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
empty line

2023-09-08 15:26 UTC, vovasalyha commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
empty line

2023-09-12 06:38 UTC, nacenik approved these changes
LGTM! 👍

2023-09-12 07:07 UTC, merged