added login and registration endpoints
SaiyaJ1N/Online-Book-Shop pull request #7
Opened 2023-09-18 22:57 UTC by SaiyaJ1N

2023-09-19 15:54 UTC, Visqe approved these changes
LGTM!

2023-09-20 12:15 UTC, andrii-hoienko requested changes
GJ, but some improvements required

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/dto/user/UserRegistrationRequestDto.java
> +    @Length(min = 1)
Please be consistent and use size annotation instead of Length

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/security/CustomUserDetailsService.java
> +                new UsernameNotFoundException("Can`t find user with email: " + username));
cant find user by username or by email?

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/security/JwtAuthenticationFilter.java
> +    private static final int INDEX_OF_TOKEN = 7;
This value could be calculated as BEARER_TOKEN_TYPE.length

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/security/JwtAuthenticationFilter.java
> +    private static final String BEARER_TOKEN_TYPE = "Bearer ";
Bad variable name. Maybe TOKEN_TYPE/BEARER will be better

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/BookService.java
> +@Service
Are you sure that you need this annotation on interface?

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/BookServiceImpl.java
> +@Component
It is better to use Service annotation for defining bean of a service class

2023-09-20 12:15 UTC, andrii-hoienko commented on src/main/java/com/onlinebookshop/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(request.getPassword()));
Please move logic of user population to separate method

2023-09-22 12:48 UTC, andrii-hoienko approved these changes
Great!

2023-09-26 07:48 UTC, merged